sgx: constrain parity-scale-codec
Else SGX CI FAILS with:

```
 error: package `proc-macro-crate v3.2.0` cannot be built because it
requires rustc 1.67.0 or newer, while the currently active rustc version
is 1.66.0-nightlyEither upgrade to rustc 1.67.0 or newer, or usecargo
update -p proc-macro-crate@3.2.0 --precise verwhere `ver` is the latest
version of `proc-macro-crate` supporting rustc 1.66.0-nightlymake[1]:
*** [Makefile:117: ../lib/libenclave.a] Error 101make[1]: Leaving
directory
'/home/runner/work/rs-common/rs-common/tests_sgx/samplecode/project_template/enclave'make:
*** [Makefile:16: enclave] Error 2
```